### ISSUE TITLE
query-replace term highlighting

### ISSUE THREAD

**Issue by dubiousdavid** [overtone/emacs-live#184]
Highlighting of the next term to be replaced using query-replace is almost unusable given the background and foreground colors are so dark.  Screenshot below.
![screen shot 2015-01-27 at 11 35 29 am](https://cloud.githubusercontent.com/assets/1327969/5922341/c05921ca-a618-11e4-90f5-d97f6c3c5918.png)

**Comment by jr0cket** [comment]
A suggested fix is to use `grey42` for the colour value of query-replace in the file `~/.emacs.d/packs/stable/colour-pack/lib/cyberpunk.el`, rather than `grey10`

The change would read:
`(query-replace ((t (:background "gray42"))))`

Thanks

**Comment by jr0cket** [comment]
@dubiousdavid the highlight colour has been updated for the query-replace function in Emacs Live.  Could you mark this issue as closed please.
