### ISSUE TITLE
Packages not auto-loaded (CIDER functionality not available)

### ISSUE THREAD

**Issue by seancorfield** [overtone/emacs-live#220]
The first sign is that `cider-browse-ns` is not available. This would be auto-loaded by `package.el` but not by Emacs Live. You can manually `(require 'cider-browse-ns)` to at least get that command and get the namespace browser up, however you can't use the doc or source commands. The former gives the error `Invalid function: (cider-doc-lookup var)`, the latter gives `Symbol's function definition is void: when-let`.

@bbatsov thought that might be a problem with `dash.el` but doing `(require 'dash)` succeeds (indicating it is loaded?) but does not solve the problems with CIDER modules not being loaded / available.

**Comment by arichiardi** [comment]
Just a note here, I am trying to keep these things up-to-date in my fork, branch [ar-stable](https://github.com/arichiardi/emacs-live/tree/ar-stable). Feel free to steal things from there. I had to add `seq` as dependency to `cider`. I am going to try to use `doc` and `source` now and report back here.

**Comment by samaaron** [comment]
I've updated to the latest CIDER on master and pulled in the `seq` lib here:

https://github.com/overtone/emacs-live/commit/8e09ab8ed1b360c60d3cc8a7737803c63fdce854

**Comment by arichiardi** [comment]
:+1:

**Comment by soulflyer** [comment]
I'm trying to get cider-inspect to work. Atm it's just giving me this error msg:
Symbol's function definition is void: cider-nrepl-send-request
Is this likely to be part of the same problem?

**Comment by arichiardi** [comment]
Maybe it's [this](https://github.com/arichiardi/emacs-live/commit/7ea02ed8b11caee812ec59ebfb2cdb112ff840c8#diff-16ee2f58d5d07299f9fb816b8121f96bR40)? I did not have time to isolate and PR. Feel free to do it if it solves!
