### ISSUE TITLE
haskell-mode error: symbol definition is void: haskell-mode-contextual-space

### ISSUE THREAD

**Issue by urbanslug** [overtone/emacs-live#233]
## outdated version of haskell-mode.

When using the current version of emacs-live and press the spacebar I get an error: symbol definition is void: `haskell-mode-contextual-space`

This is similar to the one experienced in this spacemacs issue https://github.com/syl20bnr/spacemacs/issues/227 and there are two fixes for this.

1. A quick way is to add `'(require haskell)` to `lang-pack/config/haskell-conf.el` however as explained in that https://github.com/syl20bnr/spacemacs/issues/227 an update in haskell-mode fixed it (this to be specific https://github.com/haskell/haskell-mode/issues/392).

2. Updating haskell-mode is therefore the better fix. In the newer versions of haskell-mode `haskell-simple-indent` was removed (see https://github.com/haskell/haskell-mode/wiki/Month-in-Haskell-Mode-October-2015#heads-up-cruft-removal) so the requirement in line 3 of `lang-pack/config/haskell-conf.el` shall also be removed.

Let me know if anyone has any objections to this. I will make the update on `packs/stable/` and use the git version of haskell-mode which requires Emacs 23.x and above which should be okay with emacs-live.

edit:
I wish to be assigned this issue because I have a ready fix.

**Comment by samaaron** [comment]
Hi, thanks for looking into this.

I'm happy to consider pull requests for the dev packs but not stable. Stable packs are only updated as part of a release cycle (and one is due soon).

I've currently updated most of the libs locally and am working on fixing broken/missing deps. I should have a new release of Emacs Live within a week or so.

**Comment by urbanslug** [comment]
Okay, I will send in a PR for the dev pack. I assume you will move the fix from dev to stable yourself (you haven't explicitly stated this) in about a week, right?

**Comment by samaaron** [comment]
I've already updated to the latest Haskell version locally. Would your pull request do more than this?

I'll update to stable manually when I'm happy with everything. Hopefully in around a week but maybe more depending on other commitments.

**Comment by urbanslug** [comment]
Nothing more, just remove `(require 'haskell-simple-indent)` from haskell-conf.el as explained earlier. Thank you for acting on it so quickly.

**Comment by urbanslug** [comment]
Still getting this error.
