### ISSUE TITLE
Newbie problems

### ISSUE THREAD

**Issue by pikeview** [overtone/emacs-live#258]
Hi Sam, I see below msg on trying to save a file. Please could you advise how to fix it.

![image](https://user-images.githubusercontent.com/18240627/41835981-415c57d4-7851-11e8-9362-ee4bd72ac818.png)

A similar message when I try to exit. Unable to exit emacs on windows unless I kill the process..

![image](https://user-images.githubusercontent.com/18240627/41836031-686e81b2-7851-11e8-9198-f180e3408944.png)

**Comment by sergeyromanov** [comment]
What version of Emacs are you using? Have you tried with the most recent Emacs binary (26.1)?

**Comment by pikeview** [comment]
Please ignore. I moved on to spacemacs
