### ISSUE TITLE
ac-complete not writing selected completion

### ISSUE THREAD

**Issue by tanzoniteblack** [overtone/emacs-live#39]
When auto-complete-mode is on, I can see the suggested auto-complete either through the previewed completion or the completion menu, but pressing tab (or any other method I've tried to call ac-complete, directly, or through rebinding other keys as an experiment) won't actually input the auto-completion into the file, but rather just exits from the auto-complete suggestions.  This is true in both clojure-mode and emacs-lisp-mode, but nrepl-mode is allowing me to use tab to auto-complete...but isn't showing the auto-complete list/suggestion unless I hit tab twice to have it pull up the possibilities in another buffer.

**Comment by amanas** [comment]
It was fixed for me by using this profiles.clj:

{:user {:plugins [[cider/cider-nrepl "0.9.1"]
                  [refactor-nrepl "1.1.0"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.7"]]}}

No idea the reason why.
