### ISSUE TITLE
Characters keep constantly toggling between Lower and Upper case

### ISSUE THREAD

**Issue by abaitam** [overtone/emacs-live#84]
I just installed emacs-live on Mac OS X (Mountain Lion). In the graphical version of emacs, everything is normal while in the terminal, the intro log of emacs-live as well as any file I open keeps toggling between lower and upper case all the time at rapid speed. 

How can I disable the script that does this?

Thanks

**Comment by yellowbean** [comment]
IMHO, not a big fan of this feature.
